# Generated by Django 2.1.5 on 2019-02-07 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hpux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('patch_bundle', models.CharField(max_length=100)),
            ],
        ),
    ]
