# Generated by Django 2.1.5 on 2019-02-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpux',
            name='os_type',
            field=models.CharField(default='hpux', max_length=100),
        ),
        migrations.AddField(
            model_name='hpux',
            name='status',
            field=models.CharField(default='In-Progress', max_length=100),
        ),
    ]
