# Generated by Django 2.1.5 on 2019-02-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpux', '0002_auto_20190210_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpux',
            name='change_number',
            field=models.CharField(default='CRQXXXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='hpux',
            name='os_type',
            field=models.CharField(default='hpux', max_length=50),
        ),
        migrations.AlterField(
            model_name='hpux',
            name='status',
            field=models.CharField(default='In-Progress', max_length=50),
        ),
    ]
